Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
numba.set_num_threads(4)
stuff =  df.iloc[:,4:9].sample(n=250000, replace=True, ignore_index=True)
%timeit stuff.rolling(500).mean()
%timeit stuff.rolling(500).mean(engine='numba', engine_kwargs={"parallel": True})
------------------


[31m---------------------------------------------------------------------------[39m
[31mNameError[39m                                 Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[34][39m[32m, line 2[39m
[32m      1[39m numba.set_num_threads([32m4[39m)
[32m----> [39m[32m2[39m stuff =  [43mdf[49m.iloc[:,[32m4[39m:[32m9[39m].sample(n=[32m250000[39m, replace=[38;5;28;01mTrue[39;00m, ignore_index=[38;5;28;01mTrue[39;00m)
[32m      3[39m get_ipython().run_line_magic([33m'[39m[33mtimeit[39m[33m'[39m, [33m'[39m[33mstuff.rolling(500).mean()[39m[33m'[39m)
[32m      4[39m get_ipython().run_line_magic([33m'[39m[33mtimeit[39m[33m'[39m, [33m'[39m[33mstuff.rolling(500).mean(engine=[39m[38;5;130;01m\'[39;00m[33mnumba[39m[38;5;130;01m\'[39;00m[33m, engine_kwargs=[39m[33m{[39m[33m"[39m[33mparallel[39m[33m"[39m[33m: True})[39m[33m'[39m)

[31mNameError[39m: name 'df' is not defined

